In [70]:
import torch
import numpy as np

In [32]:
torch.version.__version__

'2.0.0'

In [33]:
torch.cuda.is_available()

True

In [34]:
if torch.cuda.is_available():
    device = torch.device('cuda')  # Select the CUDA device
else:
    device = torch.device('cpu')  # Use CPU if CUDA is not available
device

device(type='cuda')

### torch.is_tensor(obj) is used to check if the object obj is a tensor

In [35]:
x = [12, 13, 23, 45, 1000]
torch.is_tensor(x)

False

## Scalar

In [36]:
scalar = torch.tensor(10)
scalar

tensor(10)

In [37]:
torch.is_tensor(scalar)

True

In [38]:
scalar.ndim

0

In [39]:
scalar.item()

10

## Vector

In [40]:
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [41]:
vector.ndim

1

In [42]:
vector.shape

torch.Size([2])

## Matrix

In [43]:
matrix = torch.tensor([[4, 5],
                       [10, 10]])
matrix

tensor([[ 4,  5],
        [10, 10]])

In [44]:
matrix.shape

torch.Size([2, 2])

In [45]:
matrix.ndim

2

## Tensor

In [46]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[9, 8, 7],
                        [6, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[9, 8, 7],
         [6, 5, 4]]])

In [47]:
tensor.shape

torch.Size([2, 2, 3])

In [48]:
tensor.ndim

3

In [49]:
tensor.device

device(type='cpu')

### moving the tensor to gpu device

In [50]:
tensor = tensor.to(device)

In [51]:
tensor.device

device(type='cuda', index=0)

In [55]:
y = torch.randn(3, 4, 5)
y

tensor([[[-0.0300, -1.7789, -0.0094,  0.0899,  1.7336],
         [-0.4895, -0.2222, -0.4070,  0.0586, -1.0605],
         [-0.8136, -0.1041, -1.5016, -0.8590,  0.6157],
         [-0.4854, -0.4267,  0.2792,  0.8016,  0.4601]],

        [[-0.2445,  0.2733, -0.3406,  0.4325, -1.3088],
         [-1.2470,  1.6084, -0.1854,  1.7713, -1.3819],
         [-0.6770, -0.6292, -0.0347, -0.4089,  1.1171],
         [ 1.4171, -1.3201, -0.5811, -1.1226, -0.7361]],

        [[-0.6622, -0.3785, -0.5022,  1.7420,  0.6342],
         [ 1.3490,  0.5941,  0.8961,  0.8130,  0.0291],
         [-1.7633,  0.1514, -0.9261, -1.3998,  0.9938],
         [-0.6378, -0.2002, -0.3249, -0.4147, -0.0884]]])

In [57]:
torch.is_tensor(y)

True

### no. of elements in the tensor object

In [58]:
torch.numel(y)

60

In [59]:
torch.is_storage(y)

False

### to create a tensor with zeroes

In [60]:
torch.zeros(4, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### to create a tensor with ones

In [61]:
torch.ones(4, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### to create matrix with diagonal elements as 1

In [63]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [64]:
torch.numel(torch.zeros(4, 4))

16

In [65]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [66]:
torch.eye(4, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [67]:
type(x)

list

In [68]:
x

[12, 13, 23, 45, 1000]

In [72]:
x1 = np.array(x)
x1

array([  12,   13,   23,   45, 1000])

### to create a tensor from numpy

In [73]:
torch.from_numpy(x1)

tensor([  12,   13,   23,   45, 1000], dtype=torch.int32)

### to create tensors between a linear space

In [76]:
torch.linspace(0, 100, steps=25, device=device)

tensor([  0.0000,   4.1667,   8.3333,  12.5000,  16.6667,  20.8333,  25.0000,
         29.1667,  33.3333,  37.5000,  41.6667,  45.8333,  50.0000,  54.1667,
         58.3333,  62.5000,  66.6667,  70.8333,  75.0000,  79.1667,  83.3333,
         87.5000,  91.6667,  95.8333, 100.0000], device='cuda:0')

### for logarithmic spacing

In [80]:
torch.logspace(-10, 10, 15)

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

### generating random numbers from uniform distribution between 0 & 1

In [81]:
torch.rand(10)

tensor([0.8885, 0.7312, 0.6327, 0.5556, 0.8692, 0.1443, 0.7677, 0.9353, 0.9596,
        0.0380])

In [84]:
torch.rand(2, 4, 5)

tensor([[[0.3457, 0.9073, 0.0410, 0.3759, 0.5736],
         [0.2340, 0.0591, 0.6056, 0.7481, 0.2315],
         [0.7114, 0.9756, 0.9423, 0.1618, 0.6725],
         [0.1765, 0.3252, 0.1182, 0.2912, 0.9382]],

        [[0.4572, 0.5440, 0.6929, 0.3016, 0.4887],
         [0.6278, 0.5838, 0.5744, 0.4595, 0.6859],
         [0.9335, 0.0628, 0.1907, 0.0418, 0.6413],
         [0.7743, 0.9439, 0.8045, 0.0525, 0.7989]]])

In [83]:
torch.rand(4, 5)

tensor([[0.9702, 0.8606, 0.7702, 0.1279, 0.9147],
        [0.2763, 0.0726, 0.7919, 0.6854, 0.9221],
        [0.2423, 0.0806, 0.1566, 0.1229, 0.8030],
        [0.1261, 0.0776, 0.8719, 0.6009, 0.6350]])

### generating random numbers from normal distribution, mean = 0, standard deviation = 1

In [82]:
torch.randn(10)

tensor([-1.3785,  0.0526, -1.7369,  0.9456, -0.2200, -0.1972, -1.7274, -0.9057,
         0.1507,  2.1945])

### generating values from a range

In [85]:
torch.randperm(10)

tensor([5, 6, 0, 2, 7, 8, 3, 9, 1, 4])

In [87]:
torch.randperm(100)

tensor([22, 24, 37,  2, 33, 78, 91, 63, 53, 64, 41, 46, 43, 16, 14, 15, 55, 76,
        28, 20, 19, 34, 50, 97, 48, 62, 30, 80, 87, 57, 77, 73, 89, 60, 32,  7,
        39, 71, 75, 69, 52, 67, 35, 26, 13, 82, 18, 99,  0, 44, 85,  4, 40, 65,
        12, 29, 90,  1, 92, 54, 17,  5, 25, 45,  6, 61,  9, 94, 93, 79, 98, 23,
        42,  8, 70, 47, 38, 68, 36, 21, 96, 58, 72, 84, 51, 31, 49, 66, 74, 59,
         3, 95, 56, 88, 83, 10, 27, 86, 11, 81])

### generating numbers from a range with steps size

In [88]:
torch.arange(10, 100, 10)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

### finding minimum and maximum values using argmin/argmax

In [90]:
d = torch.randn(4, 5)
d

tensor([[ 0.3832, -1.0318, -0.6759,  0.9739, -0.5849],
        [ 0.9588, -0.0651,  0.5399, -0.8538,  1.2066],
        [-0.3337,  1.6555, -1.0995, -1.2821,  0.7971],
        [ 0.6887, -2.1655, -2.1428, -0.0137, -0.6415]])

In [91]:
torch.argmax(d)

tensor(11)

In [92]:
torch.argmax(d, 0)

tensor([1, 2, 1, 0, 1])

In [93]:
torch.argmax(d, 1)

tensor([3, 4, 1, 0])

In [94]:
torch.argmin(d)

tensor(16)

In [95]:
torch.argmin(d, 0)

tensor([2, 3, 3, 2, 3])

In [96]:
torch.argmin(d, 1)

tensor([1, 3, 3, 1])

### to concatenate

In [98]:
x = torch.randn(4, 5)
x

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

In [100]:
torch.cat((d, x))

tensor([[ 0.3832, -1.0318, -0.6759,  0.9739, -0.5849],
        [ 0.9588, -0.0651,  0.5399, -0.8538,  1.2066],
        [-0.3337,  1.6555, -1.0995, -1.2821,  0.7971],
        [ 0.6887, -2.1655, -2.1428, -0.0137, -0.6415],
        [ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

In [101]:
torch.cat((d, x), 1)

tensor([[ 0.3832, -1.0318, -0.6759,  0.9739, -0.5849,  1.4390,  1.2823,  2.0997,
          0.2229, -0.1324],
        [ 0.9588, -0.0651,  0.5399, -0.8538,  1.2066,  1.0008,  1.3587,  0.1248,
         -0.5214,  0.1534],
        [-0.3337,  1.6555, -1.0995, -1.2821,  0.7971, -0.6738,  1.2437,  1.1193,
          0.7683, -0.1277],
        [ 0.6887, -2.1655, -2.1428, -0.0137, -0.6415,  0.7275, -0.4639,  0.1083,
          0.0121,  1.4270]])

In [102]:
torch.cat((d, x), 0)

tensor([[ 0.3832, -1.0318, -0.6759,  0.9739, -0.5849],
        [ 0.9588, -0.0651,  0.5399, -0.8538,  1.2066],
        [-0.3337,  1.6555, -1.0995, -1.2821,  0.7971],
        [ 0.6887, -2.1655, -2.1428, -0.0137, -0.6415],
        [ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

### to split into chunks

In [103]:
torch.arange(20).chunk(5)

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]),
 tensor([16, 17, 18, 19]))

In [108]:
a = torch.arange(20)
torch.chunk(a, 2)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [109]:
torch.chunk(a, 4)

(tensor([0, 1, 2, 3, 4]),
 tensor([5, 6, 7, 8, 9]),
 tensor([10, 11, 12, 13, 14]),
 tensor([15, 16, 17, 18, 19]))

### Gather function collects elements from the tensor and places them in an other tensor using an index argument. The index position is determined by the LongTensor

In [117]:
torch.gather(torch.Tensor([[11, 12], [23, 24]]), 1, torch.LongTensor([[0, 0], [1, 0]]))

tensor([[11., 11.],
        [24., 23.]])

In [119]:
a = torch.randn(4,4)
a

tensor([[-1.6003, -1.1745, -0.4361,  1.9857],
        [-0.4559,  2.7303,  1.3218, -1.5952],
        [ 0.3612,  0.7598,  0.6917,  2.2545],
        [-0.8553, -0.5173,  0.7134, -1.2407]])

In [120]:
indices = torch.LongTensor([0,2])
indices

tensor([0, 2])

In [121]:
torch.index_select(a,0,indices)

tensor([[-1.6003, -1.1745, -0.4361,  1.9857],
        [ 0.3612,  0.7598,  0.6917,  2.2545]])

In [122]:
torch.index_select(a,1,indices)

tensor([[-1.6003, -0.4361],
        [-0.4559,  1.3218],
        [ 0.3612,  0.6917],
        [-0.8553,  0.7134]])

### identify null input tensors using nonzero

In [123]:
torch.nonzero(torch.Tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

### splitting the tensor into chunks

In [124]:
torch.split(torch.arange(10),2)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]))

In [128]:
x

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

### transpose of the tensor

In [126]:
x.t()

tensor([[ 1.4390,  1.0008, -0.6738,  0.7275],
        [ 1.2823,  1.3587,  1.2437, -0.4639],
        [ 2.0997,  0.1248,  1.1193,  0.1083],
        [ 0.2229, -0.5214,  0.7683,  0.0121],
        [-0.1324,  0.1534, -0.1277,  1.4270]])

### transpose partially based on rows and column

In [129]:
x.transpose(1,1)

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

In [130]:
x.transpose(1,0)

tensor([[ 1.4390,  1.0008, -0.6738,  0.7275],
        [ 1.2823,  1.3587,  1.2437, -0.4639],
        [ 2.0997,  0.1248,  1.1193,  0.1083],
        [ 0.2229, -0.5214,  0.7683,  0.0121],
        [-0.1324,  0.1534, -0.1277,  1.4270]])

In [131]:
x.transpose(0,1)

tensor([[ 1.4390,  1.0008, -0.6738,  0.7275],
        [ 1.2823,  1.3587,  1.2437, -0.4639],
        [ 2.0997,  0.1248,  1.1193,  0.1083],
        [ 0.2229, -0.5214,  0.7683,  0.0121],
        [-0.1324,  0.1534, -0.1277,  1.4270]])

In [132]:
x.transpose(0,0)

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

### to remove a dimension , dim=1 for column and dim=0 for row

In [133]:
x

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

In [134]:
torch.unbind(x,1)

(tensor([ 1.4390,  1.0008, -0.6738,  0.7275]),
 tensor([ 1.2823,  1.3587,  1.2437, -0.4639]),
 tensor([2.0997, 0.1248, 1.1193, 0.1083]),
 tensor([ 0.2229, -0.5214,  0.7683,  0.0121]),
 tensor([-0.1324,  0.1534, -0.1277,  1.4270]))

In [136]:
torch.unbind(x,0)

(tensor([ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324]),
 tensor([ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534]),
 tensor([-0.6738,  1.2437,  1.1193,  0.7683, -0.1277]),
 tensor([ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]))

In [137]:
x

tensor([[ 1.4390,  1.2823,  2.0997,  0.2229, -0.1324],
        [ 1.0008,  1.3587,  0.1248, -0.5214,  0.1534],
        [-0.6738,  1.2437,  1.1193,  0.7683, -0.1277],
        [ 0.7275, -0.4639,  0.1083,  0.0121,  1.4270]])

In [138]:
y = torch.unbind(x,1)

In [139]:
y

(tensor([ 1.4390,  1.0008, -0.6738,  0.7275]),
 tensor([ 1.2823,  1.3587,  1.2437, -0.4639]),
 tensor([2.0997, 0.1248, 1.1193, 0.1083]),
 tensor([ 0.2229, -0.5214,  0.7683,  0.0121]),
 tensor([-0.1324,  0.1534, -0.1277,  1.4270]))